import React from 'react'
import { useState } from 'react';

const NewPage = ({ post, desc }) => {
    console.log(desc.author)
    const [contents, setContents] = useState([
        " Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nemo illum et amet! Corporis nesciunt ad vitae tempora sed quia culpa sint nihil suscipit magnam. Provident excepturi quia omnis a aliquid soluta saepe animi nemo illum voluptates labore, obcaecati molestias ratione architecto ullam quam sequi eaque dolor error dignissimos eos voluptatem? Nihil quos accusantium optio asperiores illum. Molestiae porro dicta ipsam aut doloremque? Odio recusandae ullam id aliquid, et nemo delectus similique distinctio dicta repudiandae quas in eveniet porro aperiam, aliquam laboriosam ipsam suscipit asperiores ab omnis quis. Blanditiis ipsam et quam, ratione itaque voluptatem, iure fuga molestias illo impedit delectus. Nesciunt, fugit amet totam nobis optio dolor. Vel, ut veritatis fuga magni libero quae corrupti excepturi dolores magnam expedita nemo necessitatibus deleniti, facere distinctio corporis, mollitia numquam. Voluptatem dolor magni fuga debitis in dicta mollitia vitae, repellendus libero! Reprehenderit, esse animi quia autem est itaque beatae voluptatibus impedit laudantium hic omnis quidem ut excepturi accusamus quas nobis voluptatem alias iusto magnam inventore eos eius et. Et atque sunt maiores alias voluptatem iure sequi tenetur distinctio ea expedita totam ab aut quisquam, facilis sint nobis, molestias ex corporis cum a. Nam quidem perferendis iste voluptatum mollitia facere nemo aut illum neque?",
        " Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nemo illum et amet! Corporis nesciunt ad vitae tempora sed quia culpa sint nihil suscipit magnam. Provident excepturi quia omnis a aliquid soluta saepe animi nemo illum voluptates labore, obcaecati molestias ratione architecto ullam quam sequi eaque dolor error dignissimos eos voluptatem? Nihil quos accusantium optio asperiores illum. Molestiae porro dicta ipsam aut doloremque? Odio recusandae ullam id aliquid, et nemo delectus similique distinctio dicta repudiandae quas in eveniet porro aperiam, aliquam laboriosam ipsam suscipit asperiores ab omnis quis. Blanditiis ipsam et quam, ratione itaque voluptatem, iure fuga molestias illo impedit delectus. Nesciunt, fugit amet totam nobis optio dolor. Vel, ut veritatis fuga magni libero quae corrupti excepturi dolores magnam expedita nemo necessitatibus deleniti, facere distinctio corporis, mollitia numquam. Voluptatem dolor magni fuga debitis in dicta mollitia vitae, repellendus libero! Reprehenderit, esse animi quia autem est itaque beatae voluptatibus impedit laudantium hic omnis quidem ut excepturi accusamus quas nobis voluptatem alias iusto magnam inventore eos eius et. Et atque sunt maiores alias voluptatem iure sequi tenetur distinctio ea expedita totam ab aut quisquam, facilis sint nobis, molestias ex corporis cum a. Nam quidem perferendis iste voluptatum mollitia facere nemo aut illum neque?",
        " Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nemo illum et amet! Corporis nesciunt ad vitae tempora sed quia culpa sint nihil suscipit magnam. Provident excepturi quia omnis a aliquid soluta saepe animi nemo illum voluptates labore, obcaecati molestias ratione architecto ullam quam sequi eaque dolor error dignissimos eos voluptatem? Nihil quos accusantium optio asperiores illum. Molestiae porro dicta ipsam aut doloremque? Odio recusandae ullam id aliquid, et nemo delectus similique distinctio dicta repudiandae quas in eveniet porro aperiam, aliquam laboriosam ipsam suscipit asperiores ab omnis quis. Blanditiis ipsam et quam, ratione itaque voluptatem, iure fuga molestias illo impedit delectus. Nesciunt, fugit amet totam nobis optio dolor. Vel, ut veritatis fuga magni libero quae corrupti excepturi dolores magnam expedita nemo necessitatibus deleniti, facere distinctio corporis, mollitia numquam. Voluptatem dolor magni fuga debitis in dicta mollitia vitae, repellendus libero! Reprehenderit, esse animi quia autem est itaque beatae voluptatibus impedit laudantium hic omnis quidem ut excepturi accusamus quas nobis voluptatem alias iusto magnam inventore eos eius et. Et atque sunt maiores alias voluptatem iure sequi tenetur distinctio ea expedita totam ab aut quisquam, facilis sint nobis, molestias ex corporis cum a. Nam quidem perferendis iste voluptatum mollitia facere nemo aut illum neque?",
        " Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nemo illum et amet! Corporis nesciunt ad vitae tempora sed quia culpa sint nihil suscipit magnam. Provident excepturi quia omnis a aliquid soluta saepe animi nemo illum voluptates labore, obcaecati molestias ratione architecto ullam quam sequi eaque dolor error dignissimos eos voluptatem? Nihil quos accusantium optio asperiores illum. Molestiae porro dicta ipsam aut doloremque? Odio recusandae ullam id aliquid, et nemo delectus similique distinctio dicta repudiandae quas in eveniet porro aperiam, aliquam laboriosam ipsam suscipit asperiores ab omnis quis. Blanditiis ipsam et quam, ratione itaque voluptatem, iure fuga molestias illo impedit delectus. Nesciunt, fugit amet totam nobis optio dolor. Vel, ut veritatis fuga magni libero quae corrupti excepturi dolores magnam expedita nemo necessitatibus deleniti, facere distinctio corporis, mollitia numquam. Voluptatem dolor magni fuga debitis in dicta mollitia vitae, repellendus libero! Reprehenderit, esse animi quia autem est itaque beatae voluptatibus impedit laudantium hic omnis quidem ut excepturi accusamus quas nobis voluptatem alias iusto magnam inventore eos eius et. Et atque sunt maiores alias voluptatem iure sequi tenetur distinctio ea expedita totam ab aut quisquam, facilis sint nobis, molestias ex corporis cum a. Nam quidem perferendis iste voluptatum mollitia facere nemo aut illum neque?",
        " Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nemo illum et amet! Corporis nesciunt ad vitae tempora sed quia culpa sint nihil suscipit magnam. Provident excepturi quia omnis a aliquid soluta saepe animi nemo illum voluptates labore, obcaecati molestias ratione architecto ullam quam sequi eaque dolor error dignissimos eos voluptatem? Nihil quos accusantium optio asperiores illum. Molestiae porro dicta ipsam aut doloremque? Odio recusandae ullam id aliquid, et nemo delectus similique distinctio dicta repudiandae quas in eveniet porro aperiam, aliquam laboriosam ipsam suscipit asperiores ab omnis quis. Blanditiis ipsam et quam, ratione itaque voluptatem, iure fuga molestias illo impedit delectus. Nesciunt, fugit amet totam nobis optio dolor. Vel, ut veritatis fuga magni libero quae corrupti excepturi dolores magnam expedita nemo necessitatibus deleniti, facere distinctio corporis, mollitia numquam. Voluptatem dolor magni fuga debitis in dicta mollitia vitae, repellendus libero! Reprehenderit, esse animi quia autem est itaque beatae voluptatibus impedit laudantium hic omnis quidem ut excepturi accusamus quas nobis voluptatem alias iusto magnam inventore eos eius et. Et atque sunt maiores alias voluptatem iure sequi tenetur distinctio ea expedita totam ab aut quisquam, facilis sint nobis, molestias ex corporis cum a. Nam quidem perferendis iste voluptatum mollitia facere nemo aut illum neque?",
        " Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nemo illum et amet! Corporis nesciunt ad vitae tempora sed quia culpa sint nihil suscipit magnam. Provident excepturi quia omnis a aliquid soluta saepe animi nemo illum voluptates labore, obcaecati molestias ratione architecto ullam quam sequi eaque dolor error dignissimos eos voluptatem? Nihil quos accusantium optio asperiores illum. Molestiae porro dicta ipsam aut doloremque? Odio recusandae ullam id aliquid, et nemo delectus similique distinctio dicta repudiandae quas in eveniet porro aperiam, aliquam laboriosam ipsam suscipit asperiores ab omnis quis. Blanditiis ipsam et quam, ratione itaque voluptatem, iure fuga molestias illo impedit delectus. Nesciunt, fugit amet totam nobis optio dolor. Vel, ut veritatis fuga magni libero quae corrupti excepturi dolores magnam expedita nemo necessitatibus deleniti, facere distinctio corporis, mollitia numquam. Voluptatem dolor magni fuga debitis in dicta mollitia vitae, repellendus libero! Reprehenderit, esse animi quia autem est itaque beatae voluptatibus impedit laudantium hic omnis quidem ut excepturi accusamus quas nobis voluptatem alias iusto magnam inventore eos eius et. Et atque sunt maiores alias voluptatem iure sequi tenetur distinctio ea expedita totam ab aut quisquam, facilis sint nobis, molestias ex corporis cum a. Nam quidem perferendis iste voluptatum mollitia facere nemo aut illum neque?",
        " Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nemo illum et amet! Corporis nesciunt ad vitae tempora sed quia culpa sint nihil suscipit magnam. Provident excepturi quia omnis a aliquid soluta saepe animi nemo illum voluptates labore, obcaecati molestias ratione architecto ullam quam sequi eaque dolor error dignissimos eos voluptatem? Nihil quos accusantium optio asperiores illum. Molestiae porro dicta ipsam aut doloremque? Odio recusandae ullam id aliquid, et nemo delectus similique distinctio dicta repudiandae quas in eveniet porro aperiam, aliquam laboriosam ipsam suscipit asperiores ab omnis quis. Blanditiis ipsam et quam, ratione itaque voluptatem, iure fuga molestias illo impedit delectus. Nesciunt, fugit amet totam nobis optio dolor. Vel, ut veritatis fuga magni libero quae corrupti excepturi dolores magnam expedita nemo necessitatibus deleniti, facere distinctio corporis, mollitia numquam. Voluptatem dolor magni fuga debitis in dicta mollitia vitae, repellendus libero! Reprehenderit, esse animi quia autem est itaque beatae voluptatibus impedit laudantium hic omnis quidem ut excepturi accusamus quas nobis voluptatem alias iusto magnam inventore eos eius et. Et atque sunt maiores alias voluptatem iure sequi tenetur distinctio ea expedita totam ab aut quisquam, facilis sint nobis, molestias ex corporis cum a. Nam quidem perferendis iste voluptatum mollitia facere nemo aut illum neque?",
        " Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nemo illum et amet! Corporis nesciunt ad vitae tempora sed quia culpa sint nihil suscipit magnam. Provident excepturi quia omnis a aliquid soluta saepe animi nemo illum voluptates labore, obcaecati molestias ratione architecto ullam quam sequi eaque dolor error dignissimos eos voluptatem? Nihil quos accusantium optio asperiores illum. Molestiae porro dicta ipsam aut doloremque? Odio recusandae ullam id aliquid, et nemo delectus similique distinctio dicta repudiandae quas in eveniet porro aperiam, aliquam laboriosam ipsam suscipit asperiores ab omnis quis. Blanditiis ipsam et quam, ratione itaque voluptatem, iure fuga molestias illo impedit delectus. Nesciunt, fugit amet totam nobis optio dolor. Vel, ut veritatis fuga magni libero quae corrupti excepturi dolores magnam expedita nemo necessitatibus deleniti, facere distinctio corporis, mollitia numquam. Voluptatem dolor magni fuga debitis in dicta mollitia vitae, repellendus libero! Reprehenderit, esse animi quia autem est itaque beatae voluptatibus impedit laudantium hic omnis quidem ut excepturi accusamus quas nobis voluptatem alias iusto magnam inventore eos eius et. Et atque sunt maiores alias voluptatem iure sequi tenetur distinctio ea expedita totam ab aut quisquam, facilis sint nobis, molestias ex corporis cum a. Nam quidem perferendis iste voluptatum mollitia facere nemo aut illum neque?",
        " Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nemo illum et amet! Corporis nesciunt ad vitae tempora sed quia culpa sint nihil suscipit magnam. Provident excepturi quia omnis a aliquid soluta saepe animi nemo illum voluptates labore, obcaecati molestias ratione architecto ullam quam sequi eaque dolor error dignissimos eos voluptatem? Nihil quos accusantium optio asperiores illum. Molestiae porro dicta ipsam aut doloremque? Odio recusandae ullam id aliquid, et nemo delectus similique distinctio dicta repudiandae quas in eveniet porro aperiam, aliquam laboriosam ipsam suscipit asperiores ab omnis quis. Blanditiis ipsam et quam, ratione itaque voluptatem, iure fuga molestias illo impedit delectus. Nesciunt, fugit amet totam nobis optio dolor. Vel, ut veritatis fuga magni libero quae corrupti excepturi dolores magnam expedita nemo necessitatibus deleniti, facere distinctio corporis, mollitia numquam. Voluptatem dolor magni fuga debitis in dicta mollitia vitae, repellendus libero! Reprehenderit, esse animi quia autem est itaque beatae voluptatibus impedit laudantium hic omnis quidem ut excepturi accusamus quas nobis voluptatem alias iusto magnam inventore eos eius et. Et atque sunt maiores alias voluptatem iure sequi tenetur distinctio ea expedita totam ab aut quisquam, facilis sint nobis, molestias ex corporis cum a. Nam quidem perferendis iste voluptatum mollitia facere nemo aut illum neque?",
        " Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nemo illum et amet! Corporis nesciunt ad vitae tempora sed quia culpa sint nihil suscipit magnam. Provident excepturi quia omnis a aliquid soluta saepe animi nemo illum voluptates labore, obcaecati molestias ratione architecto ullam quam sequi eaque dolor error dignissimos eos voluptatem? Nihil quos accusantium optio asperiores illum. Molestiae porro dicta ipsam aut doloremque? Odio recusandae ullam id aliquid, et nemo delectus similique distinctio dicta repudiandae quas in eveniet porro aperiam, aliquam laboriosam ipsam suscipit asperiores ab omnis quis. Blanditiis ipsam et quam, ratione itaque voluptatem, iure fuga molestias illo impedit delectus. Nesciunt, fugit amet totam nobis optio dolor. Vel, ut veritatis fuga magni libero quae corrupti excepturi dolores magnam expedita nemo necessitatibus deleniti, facere distinctio corporis, mollitia numquam. Voluptatem dolor magni fuga debitis in dicta mollitia vitae, repellendus libero! Reprehenderit, esse animi quia autem est itaque beatae voluptatibus impedit laudantium hic omnis quidem ut excepturi accusamus quas nobis voluptatem alias iusto magnam inventore eos eius et. Et atque sunt maiores alias voluptatem iure sequi tenetur distinctio ea expedita totam ab aut quisquam, facilis sint nobis, molestias ex corporis cum a. Nam quidem perferendis iste voluptatum mollitia facere nemo aut illum neque?",
        " Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nemo illum et amet! Corporis nesciunt ad vitae tempora sed quia culpa sint nihil suscipit magnam. Provident excepturi quia omnis a aliquid soluta saepe animi nemo illum voluptates labore, obcaecati molestias ratione architecto ullam quam sequi eaque dolor error dignissimos eos voluptatem? Nihil quos accusantium optio asperiores illum. Molestiae porro dicta ipsam aut doloremque? Odio recusandae ullam id aliquid, et nemo delectus similique distinctio dicta repudiandae quas in eveniet porro aperiam, aliquam laboriosam ipsam suscipit asperiores ab omnis quis. Blanditiis ipsam et quam, ratione itaque voluptatem, iure fuga molestias illo impedit delectus. Nesciunt, fugit amet totam nobis optio dolor. Vel, ut veritatis fuga magni libero quae corrupti excepturi dolores magnam expedita nemo necessitatibus deleniti, facere distinctio corporis, mollitia numquam. Voluptatem dolor magni fuga debitis in dicta mollitia vitae, repellendus libero! Reprehenderit, esse animi quia autem est itaque beatae voluptatibus impedit laudantium hic omnis quidem ut excepturi accusamus quas nobis voluptatem alias iusto magnam inventore eos eius et. Et atque sunt maiores alias voluptatem iure sequi tenetur distinctio ea expedita totam ab aut quisquam, facilis sint nobis, molestias ex corporis cum a. Nam quidem perferendis iste voluptatum mollitia facere nemo aut illum neque?",
        " Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nemo illum et amet! Corporis nesciunt ad vitae tempora sed quia culpa sint nihil suscipit magnam. Provident excepturi quia omnis a aliquid soluta saepe animi nemo illum voluptates labore, obcaecati molestias ratione architecto ullam quam sequi eaque dolor error dignissimos eos voluptatem? Nihil quos accusantium optio asperiores illum. Molestiae porro dicta ipsam aut doloremque? Odio recusandae ullam id aliquid, et nemo delectus similique distinctio dicta repudiandae quas in eveniet porro aperiam, aliquam laboriosam ipsam suscipit asperiores ab omnis quis. Blanditiis ipsam et quam, ratione itaque voluptatem, iure fuga molestias illo impedit delectus. Nesciunt, fugit amet totam nobis optio dolor. Vel, ut veritatis fuga magni libero quae corrupti excepturi dolores magnam expedita nemo necessitatibus deleniti, facere distinctio corporis, mollitia numquam. Voluptatem dolor magni fuga debitis in dicta mollitia vitae, repellendus libero! Reprehenderit, esse animi quia autem est itaque beatae voluptatibus impedit laudantium hic omnis quidem ut excepturi accusamus quas nobis voluptatem alias iusto magnam inventore eos eius et. Et atque sunt maiores alias voluptatem iure sequi tenetur distinctio ea expedita totam ab aut quisquam, facilis sint nobis, molestias ex corporis cum a. Nam quidem perferendis iste voluptatum mollitia facere nemo aut illum neque?"
    ])
    return (
        <div className='flex justify-center items-center flex-col' >
            <div className="lg:mt-28 mt-24 max-w-full w-full flex-col flex justify-center lg:items-center gap-10 px-5 lg:px-0">
                <div className="lg:w-1/2">
                    <h1 className="lg:text-6xl text-5xl mb-3">{post.title}</h1>
                    <span className="italic">{desc.uploaded_at} </span> |
                    <span> {desc.category.category_name}</span>
                </div>
                <div className="lg:w-1/2 flex flex-col">
                    <div className="flex gap-3 items-center">
                        <div class="rounded-full w-12 h-12 overflow-hidden">
                            <img src={`${desc.author.avatar}`} alt="avatar"
                                class="w-full h-full object-cover rounded-full"/>
                        </div>
                        <span className="font-semibold text-xl ">{desc.author.name}</span>
                    </div>
                </div>
                <div className="w-full lg:px-20">
                    <div className="w-full h-[5px] bg-blue-500 mb-7"></div>
                </div>
            </div>
            <div className="w-full lg:px-20 px-5">
                {
                    contents?.map((content, i) => {
                        return (
                            <p
                                key={i}
                                className="indent-14 mb-4 text-justify"
                            >
                                {content}
                            </p>
                        )
                    })
                }
            </div>
        </div>
    )
}

export default NewPage
